language: c

sudo: required
dist: bionic

addons:
  apt:
    packages:
      - libopenmpi-dev
      - openmpi-bin
      - libmetis-dev
      - libhdf5-openmpi-dev
      - libnetcdf-dev
      - libexodusii-dev
      - libexodusii5
      - libnemesis3
      - libunittest++-dev
      - libtrilinos-zoltan-dev
      - libboost-all-dev
env:
  global:
    - CCACHE_CPP2=yes
  matrix:
    - PARALLEL=ON

before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX

after_failure:
  - echo $TRAVIS_TEST_RESULT
  - cat Testing/Temporary/LastTest.log

script:
  - >
     mkdir build &&
     cd build &&
     wget https://github.com/MeshToolkit/mstk/archive/3.3.4.tar.gz &&
     tar xvzf 3.3.4.tar.gz &&
     cd MSTK-3.3.4 &&
     mkdir mstk-build && cd mstk-build &&
     cmake
     -DCMAKE_BUILD_TYPE=Release
     -DCMAKE_PREFIX_PATH=/usr/include/trilinos
     -DCMAKE_INSTALL_PREFIX=$HOME/MSTK-3.3.4-install
     -DENABLE_PARALLEL=$PARALLEL
     -DENABLE_METIS=yes
     -DENABLE_ExodusII=yes
     -DENABLE_ZOLTAN=yes
     -DENABLE_Tests=yes
     .. &&
     make VERBOSE=1 -j2 &&
     make test &&
     make install &&
     cd ../.. &&
     cmake 
     -DCMAKE_PREFIX_PATH="$HOME/MSTK-3.3.4-install;/usr/include/trilinos"
     -DCMAKE_INSTALL_PREFIX=$HOME/Jali
     -DCMAKE_BUILD_TYPE=Release
     -DENABLE_MSTK=yes
     -DBOOST_ROOT=/usr/include
     -DENABLE_Tests=yes
     ..    && 
     make VERBOSE=1 -j2 &&
     make test &&
     make install DESTDIR=$HOME

cache:
  - ccache

compiler:
  - gcc
  - clang

notifications:
  email:
    - raovgarimella@gmail.com
  on_success: never
  on_failure: always
